language: python

matrix:
    include:
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6


before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y imagemagick; fi

install:
    - pip install flake8 pylint pyroma

script:
    - flake8 pywal tests setup.py
    - pylint pywal tests setup.py
    - python setup.py test
