language: python

matrix:
    include:
        - os: osx
          language: generic
          before_install:
              - brew update
              - brew install imagemagick
              - brew install python3
              - virtualenv env -p python3
              - source env/bin/activate
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6


before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y imagemagick; fi

install:
    - pip install flake8 pylint pyroma

script:
    - flake8 pywal tests setup.py
    - pylint pywal tests setup.py
    - pyroma .
    - python setup.py test
