language: python

matrix:
    include:
        - os: osx
          language: generic
          before_install:
              - brew install imagemagick
              - brew install python3
              - brew link --overwite python3
        - os: linux
          python: 3.5
        - os: linux
          python: 3.6


before_install:
    - pip install flake8 pylint
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y imagemagick; fi

#install:
    #- pip install flake8 pylint

script:
    - flake8 pywal tests setup.py
    - pylint pywal tests setup.py
    - python setup.py test
