language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y imagemagick

install:
    - pip install flake8 pylint

script:
    - flake8 pywal tests setup.py
    - pylint pywal tests setup.py
    - python setup.py test
